NAME = wsl-tools
VERSION = 2.1.3
REPO_URL = https://github.com/zkedem/wsl-tools.git
REPO_TYPE = git
RELEASE = 1
MAINTAINER_NAME = Ziv Kedem
MAINTAINER_EMAIL = atxcorp101@gmail.com
POST_INSTALL = post-install
POST_UNINSTALL = post-uninstall
PRE_UNINSTALL = pre-uninstall
DEB_DIST = stable
LICENSE = GPL
URL = https://github.com/zkedem/wsl-tools
DESCRIPTION = A set of useful tools for WSL.
CONFIG_FILES = /etc/X11
DEB_DEPENDS = util-linux,binutils,xserver-xorg,xwayland
PACMAN_DEPENDS = util-linux,binutils,xorg-server,xorg-xwayland
RPM_DEPENDS = util-linux,binutils,xorg-x11-server-Xorg,xorg-x11-server-Xwayland
SLACKWARE_DEPENDS = util-linux,binutils,xorg-server,xorg-server-xwayland
