#!/bin/sh

if [ -n "$(command -v systemctl)" ]
then
	systemctl daemon-reload
elif [ ! -x /usr/lib/lsb/install_initd ]
then
	for l in $(seq 0 6)
	do
		rcdir="/etc/rc${l}.d/"
		find "$rcdir" -type l | grep -E -e "^${rcdir}[KS][0-9]{2}.+\.sh$" | while read -r f
		do
			[ -e "$(realpath "$f")" ] || rm -f "$f"
		done
		unset rcdir
	done
fi
