#!/bin/sh
### BEGIN INIT INFO
# Provides:          wslg-fix
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3
# Default-Stop:
# Short-Description: wslg-fix
# Description:       wslg-fix
### END INIT INFO

b0="$(basename $0)"
pidfile="/run/${b0}.pid"
[ -f "$pidfile" ] && dpid=$(cat "$pidfile")

case "$1" in
	start|restart|force-reload)
		logger -s "Starting $b0"
		[ -z "$dpid" ] && exit 0
		echo $$ > "$pidfile"
		umount /tmp/.X11-unix
		rm -rf /tmp/.X11-unix
		mkdir -m 1777 /tmp/.X11-unix
		ln -s /mnt/wslg/.X11-unix/X0 /tmp/.X11-unix/X0
		chmod 0666 /mnt/wslg/runtime-dir/wayland-0.lock
		rm -f "$pidfile"
		;;
	stop)
		logger -s "Stopping $b0"
		if [ -n "$dpid" ] && [ -n "$(ps -o args= -p $dpid)" ]
		then
			kill $dpid
			rm -f "$pidfile"
		fi
		;;
	status)
		if [ -n "$dpid" ]
		then
			if [ -z "$(ps -o args= -p $dpid)" ]
			then
				echo "$b0 dead but pid file exists" >&2
				exit 1
			fi
		else
			echo "$b0 is stopped" >&2
			exit 3
		fi
		echo "$b0 (pid $dpid) is running..." >&2
		exit 0
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
		exit 3
		;;
esac
