.TH RETURN-TOWINDOWS.PS1 1 "%DATE%" "%NAME% %VERSION%"
.SH NAME
Return\-ToWindows.ps1 \- Returns to the Windows desktop
.SH SYNOPSIS
.B Return\-ToWindows.ps1
.SH DESCRIPTION
\fBReturn\-ToWindows.ps1\fP is a Windows PowerShell script that minimizes
the X session in the foreground and restores focus to the Windows desktop.
To return to the X session, you can select its icon on the Windows
taskbar.

@NAME@ also places a desktop entry for \fBReturn\-ToWindows.ps1\fP under
the \fBSystem\fP category named \(lqReturn to Windows\(rq, which can be
accessed from your desktop environment to easily switch between Windows and
your X session.
.SH "SEE ALSO"
.BR powershell (1)
