'\" t
.\"
.\" Copyright 1984 - 1991, 1993, 1994, 1998  The Open Group
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and its
.\" documentation for any purpose is hereby granted without fee, provided that
.\" the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of The Open Group shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from The Open Group.
.TH XWSLG 1 "%DATE%" "%NAME% %VERSION%"
.SH NAME
Xwslg \- an X server for WSLg
.SH SYNOPSIS
.B Xwslg
[option ...]
.SH DESCRIPTION
\fBXwslg\fP is an X server launcher for the Windows Subsystem for Linux
GUI (WSLg) that uses \fBXwayland\fP as its backend. It is meant as a
replacement for the \fBXorg\fP X server.
.SH OPTIONS
\fBXwslg\fP accepts all the command line options described in the
\fBXserver\fP(1) and \fBXwayland\fP(1) manual pages, as well as the
\fB\-config\fP and \fB\-configdir\fP options of \fBXorg\fP(1). The
following options are also supported:
.TP 8
.BI "\-divert " cmd
Divert a command to \fBXwslg\fP. This means that, when you attempt to run
\fIcmd\fP, \fBXwslg\fP will be called instead. The command should take the
same options/arguments as a typical X server.

In most cases, if you have installed @NAME@ from your package manager,
\fBXorg\fP will be diverted to \fBXwslg\fP by default. If not, you can run
\&'\fBXwslg \-divert Xorg\fP'.

The original command will still be available as '\fIcmd\fP.diverted'.
.TP 8
\fB\-parse\fP \fIsection\fP[\fB.\fP\fIsubsection\fP|\fB@\fP\fImode\fP] \
[\fIid\fP]
Parse a configuration file specified with the \fB\-config\fP option, then
exit. This dumps \fBXwslg\fP's internal parser model of the given section
of the file to standard output, which can be useful for debugging.

A specific instance of a section may be selected with \fIid\fP, which may
be either a number or the value of an \fBIdentifier\fP entry (see the
\fBxwslg.conf\fP(5) manual page).

Subsections and modes within a section instance can also be dumped.
Subsections can be selected with a period (\fB.\fP), and modes can be
selected with a commercial at (\fB@\fP). For instance,
\&'\fBScreen.Display\fP' dumps the \fBDisplay\fP subsection of a
\fBScreen\fP section, and '\fBMonitor@1920x1080_60\fP' dumps the
\fB1920x1080_60\fP mode description from a \fBMonitor\fP section.
.TP 8
.BI "\-restore " cmd
Restore a command previously diverted to \fBXwslg\fP with the
\fB\-divert\fP option.
.PP
Furthermore, the display number option (\fB:\fP) described in the
\fBXserver\fP(1) manual page is modified as follows:
.TP 8
.BI : displaynumber
\fBXwslg\fP runs as the given \fIdisplaynumber\fP, which by default is 0.
If multiple X servers are to run simultaneously on a host, each must have
a unique display number. If a display number is already taken, \fBXwslg\fP
will automatically select the next available display number. See the
DISPLAY NAMES section of the \fBX\fP(7) manual page to learn how to
specify which display number clients should try to use.
.SH ENVIRONMENT
.TP 8
.B XWSLGCONFIG
absolute path to configuration file for "root" user; relative path to
configuration file for regular users; see \fBxwslg.conf\fP(5) for more
information.
.SH CONFIGURATION
.\" adapted from Xorg(1).
\fBXwslg\fP makes use of a configuration file called \fIxwslg.conf\fP and
configuration files with the suffix \fI.conf\fP in a directory called
\fIxwslg.conf.d\fP for its initial setup. Refer to the \fBxwslg.conf\fP(5)
manual page for information about the format of this file.
.PP
If no \fIxwslg.conf\fP file or \fIxwslg.conf.d\fP files are present,
\fBXwslg\fP assumes the same default settings as \fBXwayland\fP.
.SH FILES
.\" adapted from Xorg(1).
\fBXwslg\fP config files can be found in a range of locations. These are
documented fully in the \fBxwslg.conf\fP(5) manual page. Some common
locations are shown here.
.TP 30
.B /etc/X11/xwslg.conf
\fBXwslg\fP configuration file.
.TP 30
.B /etc/xwslg.conf
\fBXwslg\fP configuration file.
.TP 30
.B /usr/etc/xwslg.conf
\fBXwslg\fP configuration file.
.TP 30
.B /usr/lib/X11/xwslg.conf
\fBXwslg\fP configuration file.
.TP 30
.B /etc/X11/xwslg.conf.d
\fBXwslg\fP configuration directory.
.TP 30
.B /etc/xwslg.conf.d
\fBXwslg\fP configuration directory.
.TP 30
.B /usr/etc/xwslg.conf.d
\fBXwslg\fP configuration directory.
.TP 30
.B /usr/lib/X11/xwslg.conf.d
\fBXwslg\fP configuration directory.
.SH "SEE ALSO"
.BR Xorg (1),
.BR Xserver (1),
.BR Xwayland (1),
.BR xwslg.conf (5),
.BR X (7)
