.TH WSL-TOOLS-SERVICES 5 "%DATE%" "%NAME% %VERSION%"
.SH NAME
wsl\-tools\-services \- service units provided by @NAME@
.SH SYNOPSIS
.BR keepwsl.service ,
.BR wslg\-fix.service ,
.B user\-runtime\-dir@.service.d
.SH DESCRIPTION
For systemd\-based operating systems, @NAME@ includes service units that
help facilitate its core functions. These are:
.TP 4
.B keepwsl.service
Keeps the Windows Subsystem for Linux (WSL) running when a desktop
environment or graphical session is in use. Needed when full desktop
environments with display managers are to be used.
.TP 4
.B wslg\-fix.service
Ensures proper write access to the X11 socket used by the Windows
Subsystem for Linux GUI (WSLg). Needed by \fBXwslg\fP(1) to function well.
.PP
In addition, @NAME@ modifies the user manager service unit
(see \fBuser@.service\fP(5)) by adding the following lines:
.PP
.in +4n
.EX
[Service]
ExecStartPost=\-/usr/bin/rm \-f /run/user/%i/wayland\-0 \
/run/user/%i/wayland\-0.lock
.EE
.in
.SH "SEE ALSO"
.BR user@.service (5),
.BR keepwsl.service (5),
.BR wslg\-fix.service (5)
