.TH WSL-TOOLS-SERVICES 5 "%DATE%" "%NAME% %VERSION%"
.SH NAME
wsl\-tools\-services \- services provided by @NAME@
.SH SYNOPSIS
.BR keepwsl.service ,
.BR wslg\-fix.service ,
.B user\-runtime\-dir@.service.d
.br
.BR /etc/init.d/keepwsl ,
.B /etc/init.d/wslg\-fix
.SH DESCRIPTION
@NAME@ includes services that help facilitate its core functions. These
are:
.TP 4
.BR keepwsl.service ", " /etc/init.d/keepwsl
Keeps the Windows Subsystem for Linux (WSL) running when a desktop
environment or graphical session is in use. Needed when full desktop
environments with display managers are to be used.
.TP 4
.BR wslg\-fix.service ", " /etc/init.d/wslg\-fix
Ensures proper write access to the X11 socket used by the Windows
Subsystem for Linux GUI (WSLg). Needed by \fBXwslg\fP(1) to function well.
.PP
On systemd-based systems, @NAME@ also modifies the user manager service
unit (see \fBuser@.service\fP(5)) by adding the following lines:
.PP
.in +4n
.EX
[Service]
ExecStartPost=\-/usr/bin/rm \-f /run/user/%i/wayland\-0 \
/run/user/%i/wayland\-0.lock
.EE
.in
.SH "SEE ALSO"
.BR user@.service (5),
.BR keepwsl (5),
.BR wslg\-fix (5)
