.TH WSLG-FIX 5 "%DATE%" "%NAME% %VERSION%"
.SH NAME
wslg\-fix \- ensure write access to X11 socket for WSLg
.SH SYNOPSIS
.B wslg\-fix.service
.br
.BR /etc/init.d/wslg\-fix " {"
.BR start " |"
.BR stop " |"
.BR restart " |"
.BR force\-reload " |"
.BR status " }"
.SH DESCRIPTION
The X Window System, Version 11 (X11) makes use of UNIX domain sockets
(see the \fBunix\fP(7) manual page) whenever a client application is to
run on the same machine as its display server. These sockets are
accessible as files stored in the directory \fI/tmp/.X11\-unix\fP. Under
the Windows Subsystem for Linux GUI (WSLg), this directory is set as
read-only by default, which prevents more sophisticated applications, such
as desktop environments, from working. \fBwslg\-fix\fP
automatically recreates \fI/tmp/.X11\-unix\fP upon startup, sets the
correct access permissions for it and the Wayland lock file, and links the
sockets to those used by WSLg.
.PP
\fBwslg\-fix\fP should be enabled by default on all systems. If this is
not the case, and your operating system uses systemd, run
.RB ' "systemctl enable wslg\-fix" '.
.SH "SEE ALSO"
.BR wsl\-tools\-services (5)
