#!/bin/sh

argrange()
{
	for a in $(seq $1 $2)
	do
		eval "range=\"\${range:+\$range }'\${$(($a + 2))}'\""
	done
	unset a
	echo "$range"
	unset range
}

wincat()
{
	cat "$@" | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\r\n/g' | iconv -t UTF-16LE
}

privileged=0
run=exec
distroname="$(wslpath -m / | sed -E -e 's:^//.+/(.+)/$:\1:')"
i=1
uid=$(id -u -r)
b0="$(basename $0)"

while true
do
	case "$(eval "echo \${$i}")" in
		-l|-v|--list|--status|--version)
			privileged=1
			;;
		--help)
			unset run
			;;
		--this-distribution)
			eval "set -- $(argrange 1 $(($i - 1)) "$@") -d \$distroname $(argrange $(($i + 1)) $# "$@")"
			;;
	esac
	i=$(($i + 1))
	[ $i -le $# ] || break
done

if (exit $privileged) && [ -n "$run" ] && [ $uid -ne 0 ]
then
	wincat <<EOF
Superuser privileges required.
Please use '$b0 --help' for more information.
EOF
	exit 1
fi

$run /mnt/*/Windows/System32/wsl.exe "$@"
wincat <<EOF

Additional options:
    --this-distribution
        Run the current distribution.

When used from within WSL, the $b0 command requires superuser privileges.
EOF